version: '3'

services:
  mlflow_postgres:
    build:
      context: .
      dockerfile: mlflow-db/Dockerfile
    container_name: mlflow_postgres
    networks:
      - mlflow_network

  mlflow_container:
    build:
      context: .
      dockerfile: mlflow-container/Dockerfile
    container_name: mlflow_container
    networks:
      - mlflow_network
    ports:
      - "80:80"

networks:
  mlflow_network:
    driver: bridge
