version: '3'

services:
  mlflow_postgres:
    build:
      context: .
      dockerfile: mlflow-db/Dockerfile
    container_name: mlflow_postgres
    networks:
      - mlflow_network
    ports: 
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    networks:
      - mlflow_network
    ports:
      - "7654:7654"
    depends_on:
      - mlflow_container

  mlflow_container:
    build:
      context: .
      dockerfile: mlflow-container/Dockerfile
    container_name: mlflow_container
    networks:
      - mlflow_network
    ports:
      - "80:80"
  
  mlflow_exporter:
    build:
      context: .
      dockerfile: mlflow-exporter/Dockerfile
      args:
        - URI=${URI}
        - nombre_experimento=${nombre_experimento}
    container_name: mlflow_exporter
    networks:
      - mlflow_network
    ports:
      - "8000:8000"
    environment:
      - URI=${URI}
      - nombre_experimento=${nombre_experimento}

  model_training_container:
    build:
      context: .
      dockerfile: model-training/Dockerfile
      args:
        - URI=${URI}
        - nombre_experimento=${nombre_experimento}
    container_name: model_training_container
    networks:
      - mlflow_network
    depends_on:
      - mlflow_postgres
      - mlflow_container
    environment:
      - URI=${URI}
      - nombre_experimento=${nombre_experimento}

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - mlflow_network
    depends_on:
      - mlflow_container

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - mlflow_network
    depends_on:
      - prometheus

networks:
  mlflow_network:
    driver: bridge