version: '3'

services:
  mlflow-container:
    build:
      context: ./mlflow-container  # Ruta al directorio que contiene el Dockerfile del modelo MLflow
    ports:
      - "5005:5005"  # Mapeo del puerto para acceder al modelo MLflow
    volumes:
#      - ./mlruns:/mlruns  # Montar el directorio mlruns

  training-container:
    build:
      context: ./training-container  # Ruta al directorio que contiene el Dockerfile del entrenamiento
    volumes:
#      - ./data:/app/data  # Montar el directorio de datos necesario para el entrenamiento
