# global:
#   scrape_interval: 15s
#   evaluation_interval: 15s

# scrape_configs:
#   - job_name: 'mlflow'
#     static_configs:
#       - targets: ['mlflow_container:80']

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mlflow'
    static_configs:
      - targets: ['localhost:9090']  # Ajusta el nombre y puerto del contenedor del servidor exportador
