{
 "title": "Prediction application",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Precision",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "Precision{job=\"mlflow\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "Accuracy{job=\"mlflow\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(prometheus_http_requests_total[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 16 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(prometheus_http_request_duration_seconds_bucket{handler!=\"none\"}[30s]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(prometheus_http_request_duration_seconds_bucket{le=\"0.1\"}[1m]) \n/ ignoring (le) increase(prometheus_http_request_duration_seconds_count[1m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 22 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(prometheus_http_request_duration_seconds_bucket{handler!=\"none\"}[30s]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}